name: Deploy Mapbox App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Inject Mapbox Token
        run: |
          sed -i 's/<MAPBOX_ACCESS_TOKEN>/${{ secrets.MAPBOX_ACCESS_TOKEN_DEV }}/' index.html